export const idNotExistsErrMsg = "Id does not exists"
export const done = "Success"
export const usrNotExistsErrMsg = "User does not exists";
export const invalidUserErrMsg = "Invalid User name or Password"
export const inactiveUsrMsg = "Your account is deactivated, please contact your admin"
export const sendOtpMsg = "OTP Sent to registered Mobile number"
export const noUserErrMsg = "User does not exist"
export const samePwdMsg = "New Password and old password should not be same.";
export const PASSWORD_ALREADY_UPDATED = "Reset Password link is expired. Please generate a new link."
export const resetPwdMsg = "Password successfully changed";
export const otptimeexpired = "OTP expired please try again."
export const invalidOtpErrMsg = "You have entered invalid OTP";
export const noDataAvail = "No Data Available";
export const noDataAvailUpdate = "No Data Available to Update";
export const noDataAvailDelete = "No Data Available to Delete";
export const topicId = "Topic Id is Required";
export const noDoubtsAvail = "Doubts were not available";
export const updateErrnMsg = 'Data in activity_summary has been updated, but data in content_activity not updated'
export const noStudyPlanAvail = 'No Study Plan is available for this user'
export const doubtsSuccessMsg = 'Doubt Added or Updated and Doubts count was increased'
export const doubtsDeleteMsg = 'Doubt was deleted Successfully and Doubts count was decreased'
export const noMentorsAvail = "No Mentors were available.";
export const noMetaDataAvail = "Meta Data not available"
export const Success = 'Data Available'
export const NO_IN_PROGRESS_CURRICULUM = "In-progress curriculum not found"
export const UPDATED = "data updated";
export const NOT_UPDATED = "data not updated"