import express from 'express';
const router = express.Router();

import postCampusInfo from "../controllers/myCampus/campusController";
import campusCourse from "../controllers/myCampus/campusCourseBatchController";
import feePaymentMode from "../controllers/fee/feeModeController";
import feeStructure from "../controllers/fee/feeStructureController";
import defaultMenuModule from "../controllers/myCampus/defaultCampusMenuModuleController";
import campusDesignation from "../controllers/employee/campusDesignationController";
import campusGroup from "../controllers/myCampus/campusGroupController";
import defaultCountries from "../controllers/defaultCountryController";
import userRelation from "../controllers/myCampus/campusUserRelationController";
import userOnBoard from "../controllers/employee/campusUserOnBoardController";
import checkUnique from "../controllers/employee/checkUniqueController";
import timetable from "../controllers/timetableController/CampusTimetableController";
import feeCategory from "../controllers/fee/feeCategoryController";
import feeType from "../controllers/fee/feeTypeController";
import assignSubject from "../controllers/employee/assignSubjectController";
import employeeRelease from "../controllers/employee/campusEmployeeReleaseController";
import feeRule from "../controllers/fee/feeRuleController";
import feeStructRel from "../controllers/fee/feeStructureRelationController";
import information from "../controllers/information/holidayController";
import announcement from "../controllers/information/announcementController";
import news from "../controllers/information/newsController";
import noticeTemplate from "../controllers/information/noticeTemplateController";
import notice from "../controllers/information/noticeController";

router.use("/users", userOnBoard);
router.use("/feeCatOperations", feeCategory);
router.use("/feetypeOperations", feeType);
router.use("/feeStructOps", feeStructure);
router.use("/feeStructRelnOperations", feeStructRel);
router.use("/holidayinformation", information);
router.use("/announcementinformation", announcement);
router.use("/newsinformation", news);
router.use("/noticeTemplateinformation", noticeTemplate);
router.use("/noticeinformation", notice);
router.use(postCampusInfo);
router.use(campusCourse);
router.use(feePaymentMode);
router.use(defaultMenuModule);
router.use(campusDesignation);
router.use(campusGroup);
router.use(defaultCountries);
router.use(userRelation);
router.use(checkUnique);
router.use(timetable);
router.use(assignSubject);
router.use(employeeRelease);
router.use(feeRule);

export default router;
