declare module "vridhee_common_component_mf/AppInput";
declare module "vridhee_common_component_mf/AppButton";
declare module "vridhee_common_component_mf/Checbox";
declare module "vridhee_common_component_mf/Header";
declare module "vridhee_common_component_mf/Dropdown";
declare module "vridhee_common_component_mf/configJson"
declare module 'vridhee_common_component_mf/HeaderCurriculum';
declare module 'vridhee_common_component_mf/FooterCopyright';
declare module 'react-lines-ellipsis';
declare module 'react-rating-stars-component';
declare module 'vridhee_common_component_mf/AppTextarea';
declare module 'vridhee_account_mf/Spalsh';
declare module "react-loader-spinner";